name: Deploying project on GH pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setting up Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Ma première ci
        run: ls -al